function [out]=choose_cluster(label_list,cmap)

    out=[];
    if ~isempty(cmap)
        if label_list(1)~=1
            label_list=[1;label_list];
        end
        clist_hex=cellstr(rgb2hex(cmap));
        label_list=reshape(label_list,length(label_list),1);
        label_cell=cellstr(num2str(label_list-1));
        label_cell{1}='Noise';
        label_list_w_color=cellfun(@(x,y)...
            sprintf('<HTML><BODY bgcolor="%s">&emsp;&emsp;&emsp;%s&emsp;&emsp;&emsp;</BODY></HTML>',x,y),...
            clist_hex,label_cell,'UniformOutput',false);
        label_list_w_color=[label_list_w_color;'New cluster'];
    else
        label_list_w_color={'New cluster'};
    end
    f=figure('units','normalized','outerposition',[.4 .4 .15 .4],...
    'Name','Select Cluster to Assign','ToolBar','none','MenuBar','none');
    label_list_box=uicontrol('Style','listbox',...
    'Units','Normalized',...
        'Position',[.1,.2,.8,.75],...
        'Max',1,...
        'Min',1,...
        'Value',length(label_list)+1,...
        'String',label_list_w_color);
    listbox_pos=label_list_box.Position;
    button_h=.06;
    button_sep=0.02;
    button_w=listbox_pos(3)/2-button_sep;
    ok_button=uicontrol('Style','pushbutton',...
        'Units','Normalized',...
        'Position',[listbox_pos(1),  listbox_pos(2)-button_h-button_sep,...
        button_w,button_h],...
        'String','OK',...
        'Callback',{@ok_press,out});
    cancel_button=uicontrol('Style','pushbutton',...
        'Units','Normalized',...
        'Position',[listbox_pos(1)+ok_button.Position(3)+button_sep, ...
        listbox_pos(2)-button_h-button_sep,...
        button_w,button_h],...
        'String','Cancel',...
        'Callback','uiresume(gcbf)');
    uiwait(f);
    close(f);


function ok_press(varargin)
    if label_list_box.Value>length(label_list)
        out='New cluster';
    elseif label_list_box.Value==1
        out='Noise';
    else
        out=label_list(label_list_box.Value);
    end
    
    uiresume(gcbf);
    
end

end