function [out]=selectTestORNbasis()
    
    
    orns={'33b','45a','83a','35a','42a','59a','1a','45b','24a','67b','85c','13a','30a','82a','22c','42b','74a','94a'};
    
    out=[];
    
    
    f=figure('units','normalized','outerposition',[.4 .4 .25 .5],...
    'Name','Select ORNs to include','ToolBar','none','MenuBar','none');
    label_list_box=uicontrol('Style','listbox',...
    'Units','Normalized',...
        'Position',[.1,.2,.8,.75],...
        'Max',length(orns),...
        'Min',1,...
        'Value',1,...
        'String',orns,...
        'FontSize',12);
    listbox_pos=label_list_box.Position;
    button_h=.06;
    button_sep=0.02;
    button_w=listbox_pos(3)/2-button_sep;
    ok_button=uicontrol('Style','pushbutton',...
        'Units','Normalized',...
        'Position',[listbox_pos(1),  listbox_pos(2)-button_h-button_sep,...
        button_w,button_h],...
        'String','OK',...
        'Callback',{@ok_press,out});
    cancel_button=uicontrol('Style','pushbutton',...
        'Units','Normalized',...
        'Position',[listbox_pos(1)+ok_button.Position(3)+button_sep, ...
        listbox_pos(2)-button_h-button_sep,...
        button_w,button_h],...
        'String','Cancel',...
        'Callback','uiresume(gcbf)');

    uiwait(f);
    close(f);


function ok_press(varargin)
        out=orns(label_list_box.Value);
    
    uiresume(gcbf);
    
end

end