function [out]=selectTestOdorSet(odor_seq,odor_inf)
%returns out=[odor,conc] indicies of odors not being included in test odor set.
    if ~exist('odor_inf','var')
        odor_inf=load('odor_inf.mat');            
    end
    odor_list=odor_inf.odor_list;
    odor_concentration_list=odor_inf.odor_concentration_list;
    odor_colormap=odor_inf.odor_colormap;
    
    odors=unique(odor_seq(odor_seq>0),'stable');

    odorconc=cell(length(odors),1);
    for ii=1:length(odors)
        [odorname ,conc,inds(ii,:)]= compute_odor_conc(odors(ii),odor_inf);
       odorconc{ii}=sprintf('%s %s',conc,odorname);
    end
    cmap=odor_colormap(odors,:);
    out=[];
    
    if ~isempty(cmap)    
        clist_hex=cellstr(rgb2hex(cmap));
        odorList_w_color=cellfun(@(x,y)...
            sprintf('<HTML><BODY bgcolor="%s">&emsp;&emsp;&emsp;%s&emsp;&emsp;&emsp;</BODY></HTML>',x,y),...
            clist_hex,odorconc,'UniformOutput',false);
    end
    f=figure('units','normalized','outerposition',[.4 .4 .25 .4],...
    'Name','Select Test Odors','ToolBar','none','MenuBar','none');
    label_list_box=uicontrol('Style','listbox',...
    'Units','Normalized',...
        'Position',[.1,.2,.8,.75],...
        'Max',length(odorconc),...
        'Min',1,...
        'Value',1,...
        'String',odorList_w_color,...
        'FontSize',12);
    listbox_pos=label_list_box.Position;
    button_h=.06;
    button_sep=0.02;
    button_w=listbox_pos(3)/2-button_sep;
    ok_button=uicontrol('Style','pushbutton',...
        'Units','Normalized',...
        'Position',[listbox_pos(1),  listbox_pos(2)-button_h-button_sep,...
        button_w,button_h],...
        'String','OK',...
        'Callback',{@ok_press,out});
    cancel_button=uicontrol('Style','pushbutton',...
        'Units','Normalized',...
        'Position',[listbox_pos(1)+ok_button.Position(3)+button_sep, ...
        listbox_pos(2)-button_h-button_sep,...
        button_w,button_h],...
        'String','Cancel',...
        'Callback','uiresume(gcbf)');

    uiwait(f);
    close(f);


function ok_press(varargin)
    selected=label_list_box.Value;
    
    out=inds(~ismember(1:length(odorconc),selected),:);
    uiresume(gcbf);
    
end

end